// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs4yabDU7dn4wR0F5ma3UYas4HlreE4mM',
    appId: '1:988163815731:android:17acea81724509aa6aa646',
    messagingSenderId: '988163815731',
    projectId: 'jresteaujus',
    databaseURL: 'https://jresteaujus-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jresteaujus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtTUEIhYlImCM0tngRRjcwpcQB_3Q3rW0',
    appId: '1:988163815731:ios:4d64787c658f9cf66aa646',
    messagingSenderId: '988163815731',
    projectId: 'jresteaujus',
    databaseURL: 'https://jresteaujus-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jresteaujus.appspot.com',
    iosClientId: '988163815731-vsvjr4cf7ibdm9aa9o53b5eg1b2oes2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutevents',
  );
}
